name: Run all scrapers and merge

on:
  workflow_dispatch:   # מאפשר הפעלה ידנית
  schedule:
    - cron: "0 */12 * * *"   # ירוץ כל 12 שעות

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # מנקה את ה-runner מכל קומיט או קובץ מקומי ישן
      - name: Reset to remote main
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main
          git clean -fdx

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements_scraper.txt

      - name: Run all scrapers
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python run_all.py

      - name: Commit & push updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add merged_jobs.csv
          git commit -m "Auto update merged_jobs.csv" || echo "No changes to commit"
          git push origin HEAD:main
