name: Run all scrapers and merge

on:
  workflow_dispatch:         # הפעלה ידנית
  schedule:
    - cron: "0 */12 * * *"   # כל 12 שעות

concurrency:
  group: csv-update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # חשוב כדי שנוכל לעשות rebase/pull כראוי

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_scraper.txt

      - name: Run all scrapers
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python run_all.py

      - name: Commit & push updated CSV (pull --rebase + retry)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -e

          # הזדהות
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

          # ודא/י שאנחנו על main ומעודכנים לפני שנוגעים בקבצים
          git checkout main
          git fetch origin main
          git pull --rebase origin main

          # הוספת התוצר
          git add merged_jobs.csv

          # אם אין שינוי — לצאת בשקט
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Auto update merged_jobs.csv"

          # ניסיון דחיפה עם טיפול במרוץ (עד 3 ניסיונות)
          n=0
          until [ $n -ge 3 ]
          do
            if git push origin HEAD:main; then
              echo "Pushed successfully"
              break
            fi

            echo "Push failed (likely non-fast-forward). Rebasing and retrying... ($((n+1))/3)"
            # למשוך את ה־HEAD האחרון ולנגן את הקומיט שלנו מעליו
            git fetch origin main
            if ! git rebase origin/main; then
              echo "Rebase conflict; resetting softly to remote HEAD and recommitting file"
              git rebase --abort || true
              # לשמור את השינויים ב־index, לבסס על origin/main וליצור קומיט חדש נקי
              git reset --soft origin/main
              git add merged_jobs.csv
              git commit -m "Auto update merged_jobs.csv"
            fi
            n=$((n+1))
            sleep 2
          done

          if [ $n -ge 3 ]; then
            echo "Failed to push after 3 attempts"; exit 1
          fi
