name: Run all scrapers and merge

on:
  workflow_dispatch:     # הפעלה ידנית
  schedule:
    - cron: "0 */12 * * *"   # כל 12 שעות

concurrency:
  group: csv-update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # חשוב לריבייס

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_scraper.txt

      - name: Run all scrapers
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python run_all.py

      - name: Commit & push updated CSV (rebase + force-with-lease)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # הזדהות מול GitHub עם האסימון המובנה של Actions
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

          # ודא/י שאנחנו מעודכנים מול origin/main
          git fetch origin main
          git checkout main

          # הוספה וקומיט רק אם יש שינוי
          git add merged_jobs.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Auto update merged_jobs.csv"

          # ריבייס על HEAD האחרון ב־remote
          git fetch origin main
          git rebase origin/main

          # דחיפה בטוחה יחסית (לא תדרוס אם מישהו דחף מאז הפאץ' האחרון)
          git push --force-with-lease origin HEAD:main
