name: Run all scrapers and open PR
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: scrapers-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Sync with remote main
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_scraper.txt

      - name: Run all scrapers
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python run_all.py

      - name: Check if merged_jobs.csv changed
        id: changes
        run: |
          if git diff --quiet -- merged_jobs.csv; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi

      - name: Commit to new branch and open PR
        if: steps.changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # יצירת ענף חדש
          TS=$(date +%s)
          BRANCH="auto-update-${TS}"
          git checkout -b "$BRANCH"

          # הוספת הקובץ ו-commit
          git add merged_jobs.csv
          git commit -m "Auto update merged_jobs.csv [skip ci]"

          # דחיפה של הענף
          git push --set-upstream origin "$BRANCH"

          # פתיחת PR ל-main
          gh pr create \
            --title "Auto update: merged_jobs.csv" \
            --body "Automated update of merged_jobs.csv generated by GitHub Actions." \
            --base main \
            --head "$BRANCH" \
            --label "automation,data-update"
