name: Run all scrapers and open PR
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # חשוב: להסתנכרן עם main לפני שיוצרים שינויים
      - name: Prepare repo (sync with origin/main)
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_scraper.txt

      - name: Run all scrapers
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python run_all.py

      # לבדוק אם באמת נוצרו שינויים אחרי הריצה
      - name: Check if file changed
        id: changes
        run: |
          # אם רוצים לבדוק רק את merged_jobs.csv אפשר להוסיף:
          # if git diff --quiet -- merged_jobs.csv; then ...
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi

      - name: Configure Git
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create PR if changes exist
        if: steps.changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="auto-update-$TIMESTAMP"

          git checkout -b "$BRANCH_NAME"
          # לצמצם את ה-commit לקובץ/ים הרלוונטיים:
          git add merged_jobs.csv
          git commit -m "Auto update merged_jobs.csv [skip ci]"
          git push origin "$BRANCH_NAME"

          gh pr create \
            --title "Auto update: merged_jobs.csv" \
            --body "Automated update of merged_jobs.csv generated by GitHub Actions." \
            --base main \
            --head "$BRANCH_NAME" \
            --label "automation,data-update"
