name: Run all scrapers and merge (PR auto-merge)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_scraper.txt
      - name: Run all scrapers
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python run_all.py
      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet HEAD; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Create and push branch with changes
        if: steps.changes.outputs.no_changes == 'false'
        run: |
          BRANCH_NAME="automation/update-csv-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          git add merged_jobs.csv
          git commit -m "Auto update merged_jobs.csv"
          git push origin "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        id: push_branch
      - name: Create Pull Request
        if: steps.changes.outputs.no_changes == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Auto update merged_jobs.csv',
              head: '${{ steps.push_branch.outputs.branch_name }}',
              base: 'main',
              body: 'Automated update of merged_jobs.csv generated by GitHub Actions.'
            })
